import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { pearsonCorrelation } from "../../../shared/analytics";
import { BarChart3, FileUp, Footprints, Save, TrendingUp } from "lucide-react";
import { ChangeEvent, useMemo, useRef, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";

type Entry = { type: "seat" | "focus"; startedAt: Date; elapsedSeconds: number; status: "running" | "paused" | "completed" };
type StepImport = { dateKey: string; steps: number };
const asDate = (value: Date | string) => value instanceof Date ? value : new Date(value);
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const toNumber = (value: string) => Number(value.replace(/[\s,]/g, ""));

function parseDate(value: string): string | null { const match = value.match(/(20\d{2})[.\-/년\s]+\s?(\d{1,2})[.\-/월\s]+\s?(\d{1,2})/); return match ? `${match[1]}-${match[2].padStart(2, "0")}-${match[3].padStart(2, "0")}` : null; }
function parseStepFile(text: string): StepImport[] {
  const totals = new Map<string, number>();
  if (/<Record\b/i.test(text)) {
    const records = Array.from(text.matchAll(/<Record\b[^>]*type="[^"]*StepCount[^"]*"[^>]*>/gi));
    const intervals = new Map<string, number>();
    records.forEach(match => { const tag = match[0]; const date = parseDate(tag.match(/startDate="([^"]+)"/i)?.[1] || ""); const end = tag.match(/endDate="([^"]+)"/i)?.[1] || ""; const steps = Number(tag.match(/value="([\d.]+)"/i)?.[1]); if (date && Number.isFinite(steps)) { const key = `${date}:${tag.match(/startDate="([^"]+)"/i)?.[1]}:${end}`; intervals.set(key, Math.max(intervals.get(key) || 0, Math.round(steps))); } });
    intervals.forEach((steps, key) => { const date = key.slice(0, 10); totals.set(date, (totals.get(date) || 0) + steps); });
  } else {
    const rows = text.split(/\r?\n/).filter(Boolean).map(line => line.split(/[\t,;]/).map(value => value.trim()));
    const header = rows[0]?.map(value => value.toLowerCase()) || [];
    const dateIndex = header.findIndex(value => /date|날짜|day/.test(value)); const stepIndex = header.findIndex(value => /step|걸음|count/.test(value));
    rows.slice(dateIndex >= 0 || stepIndex >= 0 ? 1 : 0).forEach(row => { const date = parseDate(row[dateIndex >= 0 ? dateIndex : 0] || "") || row.map(parseDate).find(Boolean); const steps = toNumber(row[stepIndex >= 0 ? stepIndex : row.length - 1] || ""); if (date && Number.isFinite(steps) && steps >= 0) totals.set(date, Math.round(steps)); });
  }
  return Array.from(totals, ([dateKey, steps]) => ({ dateKey, steps })).sort((a, b) => a.dateKey.localeCompare(b.dateKey));
}

export default function Analytics() {
  const utils = trpc.useUtils(); const fileRef = useRef<HTMLInputElement>(null); const [steps, setSteps] = useState(""); const [date, setDate] = useState(() => dateKey(new Date()));
  const { data: rawEntries = [] } = trpc.tracking.list.useQuery(); const { data: storedSteps = [], isLoading } = trpc.tracking.steps.list.useQuery();
  const entries = rawEntries as Entry[];
  const upsert = trpc.tracking.steps.upsert.useMutation({ onSuccess: () => { toast.success("걸음 수를 저장했어요."); setSteps(""); void utils.tracking.steps.list.invalidate(); }, onError: error => toast.error(error.message) });
  const importSteps = trpc.tracking.steps.import.useMutation({ onSuccess: result => { toast.success(`${result.count}일의 걸음 수를 반영했어요.`); void utils.tracking.steps.list.invalidate(); }, onError: error => toast.error(error.message) });
  const chartData = useMemo(() => { const days = Array.from({ length: 14 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (13 - index)); return date; }); return days.map(day => { const key = dateKey(day); const records = entries.filter(entry => entry.status === "completed" && dateKey(asDate(entry.startedAt)) === key); return { key, date: new Intl.DateTimeFormat("ko-KR", { month: "numeric", day: "numeric" }).format(day), steps: storedSteps.find(item => item.dateKey === key)?.steps ?? null, focusMinutes: Math.round(records.filter(entry => entry.type === "focus").reduce((sum, entry) => sum + entry.elapsedSeconds, 0) / 60), seatMinutes: Math.round(records.filter(entry => entry.type === "seat").reduce((sum, entry) => sum + entry.elapsedSeconds, 0) / 60) }; }); }, [entries, storedSteps]);
  const focusPairs = chartData.filter(item => item.steps !== null).map(item => ({ x: item.steps as number, y: item.focusMinutes }));
  const seatPairs = chartData.filter(item => item.steps !== null).map(item => ({ x: item.steps as number, y: item.seatMinutes }));
  const focusCorrelation = pearsonCorrelation(focusPairs);
  const seatCorrelation = pearsonCorrelation(seatPairs);
  const focusTotal = chartData.reduce((total, item) => total + item.focusMinutes, 0); const seatTotal = chartData.reduce((total, item) => total + item.seatMinutes, 0); const stepDays = chartData.filter(item => item.steps !== null).length;
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const reader = new FileReader(); reader.onload = () => { const parsed = parseStepFile(String(reader.result || "")); if (!parsed.length) return toast.error("날짜와 걸음 수를 찾지 못했어요. CSV 또는 Apple Health XML 형식을 확인해 주세요."); importSteps.mutate(parsed); }; reader.onerror = () => toast.error("파일을 읽지 못했어요."); reader.readAsText(file); };
  const saveManual = () => { const numeric = toNumber(steps); if (!date || !Number.isInteger(numeric) || numeric < 0 || numeric > 200000) return toast.error("0~200,000 사이의 정수 걸음 수를 입력해 주세요."); upsert.mutate({ dateKey: date, steps: numeric }); };
  const describeCorrelation = (correlation: number | null, target: "집중" | "좌석") => correlation === null ? `${target} 시간 분석을 위한 데이터가 더 필요해요.` : correlation >= .5 ? `활동량이 높을수록 ${target} 시간도 함께 늘어나는 경향이에요.` : correlation <= -.5 ? `활동량이 높을수록 ${target} 시간은 줄어드는 경향이에요.` : `걸음 수와 ${target} 시간 사이에 뚜렷한 선형 경향은 아직 없어요.`;
  return <div className="animate-page-in"><header><p className="text-[10px] font-bold tracking-[0.16em] text-[#22aa62]">WEEKLY RHYTHM REPORT</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.08em] text-[#18332a] sm:text-4xl">이번 주 리듬 리포트</h1><p className="mt-2 text-sm leading-6 text-[#71877e]">내 휴대폰의 걸음 수와 직접 기록한 시간을 같은 흐름에서 살펴보세요.</p></header>
    <section className="mt-7 grid gap-4 xl:grid-cols-[.92fr_1.08fr]"><div className="rounded-[28px] bg-[#18332a] p-5 text-white shadow-[0_14px_36px_rgba(21,86,66,0.12)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold tracking-[0.14em] text-[#a9f5c9]">AI RHYTHM COACH</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.06em]">움직임과 시간의 관계</h2></div><TrendingUp className="h-5 w-5 text-[#3ddc84]" /></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4"><p className="text-[10px] font-bold tracking-[0.13em] text-[#b8d1c6]">걸음 수 × 집중 시간</p><p className="mt-1 font-mono text-3xl font-extrabold tracking-[-0.08em] text-[#3ddc84]">{focusCorrelation === null ? "—" : focusCorrelation.toFixed(2)}</p><p className="mt-2 text-[11px] leading-5 text-[#d5e4dc]">{describeCorrelation(focusCorrelation, "집중")}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-[10px] font-bold tracking-[0.13em] text-[#b8d1c6]">걸음 수 × 좌석 시간</p><p className="mt-1 font-mono text-3xl font-extrabold tracking-[-0.08em] text-[#3ddc84]">{seatCorrelation === null ? "—" : seatCorrelation.toFixed(2)}</p><p className="mt-2 text-[11px] leading-5 text-[#d5e4dc]">{describeCorrelation(seatCorrelation, "좌석")}</p></div></div><p className="mt-4 text-[11px] leading-5 text-[#c1d4cb]">걸음 수가 기록된 {stepDays}일과 해당 일의 시간 기록을 사용합니다. 각 분석은 2일 이상이고 값의 변화가 있어야 계산됩니다.</p></div>
      <div className="grid grid-cols-3 gap-3 rounded-[28px] border border-[#e6e2d9] bg-[#fbfaf7] p-5 shadow-[0_14px_36px_rgba(45,55,50,0.05)] sm:p-6"><div className="rounded-2xl bg-[#edf2ee] p-4"><Footprints className="h-4 w-4 text-[#52786c]" /><p className="mt-6 text-[10px] font-bold text-[#7c8881]">걸음 수 기록</p><p className="mt-1 text-xl font-extrabold tracking-[-0.06em] text-[#445750]">{stepDays}<span className="ml-1 text-xs">일</span></p></div><div className="rounded-2xl bg-[#f5ede2] p-4"><BarChart3 className="h-4 w-4 text-[#9a754d]" /><p className="mt-6 text-[10px] font-bold text-[#8a8177]">집중 누적</p><p className="mt-1 text-xl font-extrabold tracking-[-0.06em] text-[#554f46]">{Math.floor(focusTotal / 60)}<span className="ml-1 text-xs">시간</span></p></div><div className="rounded-2xl bg-[#f0f0ec] p-4"><TrendingUp className="h-4 w-4 text-[#777d75]" /><p className="mt-6 text-[10px] font-bold text-[#838780]">좌석 누적</p><p className="mt-1 text-xl font-extrabold tracking-[-0.06em] text-[#505853]">{Math.floor(seatTotal / 60)}<span className="ml-1 text-xs">시간</span></p></div></div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-[28px] border border-[#e6e2d9] bg-[#fbfaf7] p-5 shadow-[0_14px_36px_rgba(45,55,50,0.05)] sm:p-6"><div><p className="text-[10px] font-bold tracking-[0.14em] text-[#9c7d57]">DAILY ACTIVITY</p><h2 className="mt-2 text-lg font-extrabold tracking-[-0.06em] text-[#2a3a3b]">걸음 수 추세</h2></div><div className="mt-5 h-[245px]">{isLoading ? <div className="h-full animate-pulse rounded-2xl bg-[#f0efea]" /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="stepsGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#63867a" stopOpacity={.35} /><stop offset="100%" stopColor="#63867a" stopOpacity={.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#ece8df" strokeDasharray="3 4" /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#9b9a91" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#9b9a91" }} width={35} /><Tooltip formatter={(value: number) => [`${value.toLocaleString()}걸음`, "걸음 수"]} contentStyle={{ borderRadius: 14, border: "1px solid #e6e2d9", fontSize: 12 }} /><Area type="monotone" dataKey="steps" stroke="#52786c" strokeWidth={2.5} fill="url(#stepsGradient)" connectNulls /></AreaChart></ResponsiveContainer>}</div></div>
      <div className="rounded-[28px] border border-[#e6e2d9] bg-[#fbfaf7] p-5 shadow-[0_14px_36px_rgba(45,55,50,0.05)] sm:p-6"><div><p className="text-[10px] font-bold tracking-[0.14em] text-[#9c7d57]">FOCUS / SEAT</p><h2 className="mt-2 text-lg font-extrabold tracking-[-0.06em] text-[#2a3a3b]">시간 기록 추세</h2></div><div className="mt-5 h-[245px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} barGap={2}><CartesianGrid vertical={false} stroke="#ece8df" strokeDasharray="3 4" /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#9b9a91" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#9b9a91" }} width={26} /><Tooltip formatter={(value: number, name: string) => [`${value}분`, name === "focusMinutes" ? "집중" : "좌석"]} contentStyle={{ borderRadius: 14, border: "1px solid #e6e2d9", fontSize: 12 }} /><Bar dataKey="focusMinutes" name="집중" fill="#52786c" radius={[5, 5, 0, 0]} /><Bar dataKey="seatMinutes" name="좌석" fill="#d4a66e" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className="rounded-[28px] bg-[#ece7dc] p-5 sm:p-6"><p className="text-[10px] font-bold tracking-[0.14em] text-[#987c59]">MANUAL ENTRY</p><h2 className="mt-2 text-lg font-extrabold tracking-[-0.06em] text-[#3d4640]">오늘의 걸음 수 저장</h2><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><div><Label className="text-[10px] font-bold text-[#716e67]">날짜</Label><Input type="date" value={date} onChange={event => setDate(event.target.value)} className="mt-2 h-10 border-[#dcd6ca] bg-[#fbfaf7] text-xs" /></div><div><Label className="text-[10px] font-bold text-[#716e67]">걸음 수</Label><Input inputMode="numeric" value={steps} onChange={event => setSteps(event.target.value)} placeholder="예: 6,420" className="mt-2 h-10 border-[#dcd6ca] bg-[#fbfaf7] text-sm" /></div><Button onClick={saveManual} disabled={upsert.isPending} className="mt-auto h-10 rounded-xl bg-[#426a61] text-white hover:bg-[#355a52]"><Save className="mr-2 h-4 w-4" />저장</Button></div></div>
      <div className="rounded-[28px] border border-dashed border-[#d5c9b8] bg-[#fbfaf7] p-5 sm:p-6"><p className="text-[10px] font-bold tracking-[0.14em] text-[#9c7d57]">HEALTH DATA IMPORT</p><h2 className="mt-2 text-lg font-extrabold tracking-[-0.06em] text-[#2a3a3b]">휴대폰 건강 데이터 불러오기</h2><p className="mt-2 text-xs leading-5 text-[#7d837c]">날짜와 걸음 수 열이 있는 CSV·TSV 파일, 또는 Apple Health 내보내기 XML을 불러올 수 있어요. 파일 원본은 저장하지 않고 일별 걸음 수만 계정에 저장합니다.</p><input ref={fileRef} type="file" accept=".csv,.tsv,.txt,.xml,text/csv,text/plain,application/xml" onChange={handleFile} className="hidden" /><Button variant="outline" onClick={() => fileRef.current?.click()} disabled={importSteps.isPending} className="mt-4 rounded-xl border-[#cfc8bb] bg-white text-[#52655f] hover:bg-[#f2f0eb]"><FileUp className="mr-2 h-4 w-4" />파일 선택</Button></div></section>
  </div>;
}
