import { startLogin } from "@/const";
import { Activity, ArrowRight, CalendarRange, Footprints, Timer } from "lucide-react";

const benefits = [
  { icon: Timer, title: "시간을 온전히 기록", description: "좌석과 집중 시간을 끊김 없이 남깁니다." },
  { icon: CalendarRange, title: "흐름을 직접 편집", description: "캘린더에서 기록을 끌어 시간대를 조정합니다." },
  { icon: Footprints, title: "움직임까지 함께 해석", description: "걸음 수와 시간의 관계를 나란히 살펴봅니다." },
];

export default function Landing() {
  return <main className="relative min-h-screen overflow-hidden bg-[#f7f5ef] px-5 py-6 text-[#27343a] sm:px-8 lg:px-12"><div className="pointer-events-none absolute -left-32 top-24 h-96 w-96 rounded-full bg-[#dde9e0]/70 blur-3xl" /><div className="pointer-events-none absolute right-[-10rem] top-[-8rem] h-[34rem] w-[34rem] rounded-full bg-[#eee2ce]/80 blur-3xl" />
    <div className="relative mx-auto max-w-6xl"><header className="flex items-center justify-between"><div><p className="text-lg font-extrabold tracking-[-0.08em]">시작점</p><p className="mt-1 text-[9px] font-bold tracking-[0.22em] text-[#9b8771]">DAILY RHYTHM</p></div><button onClick={() => startLogin()} className="rounded-full border border-[#d9d7cf] bg-[#fbfaf7]/90 px-4 py-2.5 text-xs font-bold text-[#4d605a] shadow-sm transition hover:border-[#6d8c83] hover:bg-white active:scale-[0.97]">로그인</button></header>
      <section className="grid min-h-[70vh] items-center gap-14 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#d7e3db] bg-[#edf3ee] px-3 py-1.5 text-[10px] font-bold tracking-[0.1em] text-[#527168]"><span className="h-1.5 w-1.5 rounded-full bg-[#b48858]" />PERSONAL PRODUCTIVITY</div><h1 className="mt-7 text-[42px] font-extrabold leading-[1.04] tracking-[-0.095em] text-[#25353a] sm:text-[64px]">오늘의 흐름을<br /><span className="text-[#426a61]">가볍고 또렷하게.</span></h1><p className="mt-6 max-w-xl text-[15px] leading-7 text-[#6b746e]">앉아 있는 시간, 몰입한 시간, 그리고 걸음 수까지. 흩어진 하루를 한 곳에 기록하고 나만의 리듬으로 정리하세요.</p><button onClick={() => startLogin()} className="mt-9 inline-flex items-center gap-2 rounded-2xl bg-[#385f57] px-5 py-3.5 text-sm font-bold text-white shadow-[0_14px_28px_rgba(56,95,87,0.2)] transition hover:bg-[#2f524b] active:scale-[0.97]">내 기록 시작하기 <ArrowRight className="h-4 w-4" /></button></div>
        <div className="rounded-[32px] border border-white/80 bg-[#fbfaf7]/85 p-5 shadow-[0_28px_80px_rgba(58,67,62,0.13)] backdrop-blur sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[0.14em] text-[#aa8a62]">YOUR DAY</p><p className="mt-1 text-lg font-extrabold tracking-[-0.06em]">나만의 시간 기록</p></div><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e8eee9] text-[#41665f]"><Activity className="h-5 w-5" /></div></div><div className="mt-7 rounded-2xl bg-[#263940] p-5 text-white"><p className="text-[10px] font-bold tracking-[0.12em] text-[#bccfc5]">오늘의 시작</p><p className="mt-4 text-2xl font-extrabold tracking-[-0.07em]">한 번의 기록이<br />하루의 흐름이 됩니다.</p><div className="mt-6 flex gap-2"><span className="rounded-lg bg-white/10 px-3 py-2 text-[11px] font-semibold">좌석 타이머</span><span className="rounded-lg bg-white/10 px-3 py-2 text-[11px] font-semibold">집중 세션</span></div></div><div className="mt-4 grid grid-cols-3 gap-3">{benefits.map(({ icon: Icon, title }) => <div key={title} className="rounded-2xl bg-[#f2f0eb] p-3"><Icon className="h-4 w-4 text-[#69877d]" /><p className="mt-4 text-[11px] font-bold leading-4 text-[#56615d]">{title}</p></div>)}</div></div>
      </section>
      <section className="grid gap-3 pb-8 sm:grid-cols-3">{benefits.map(({ icon: Icon, title, description }) => <div key={title} className="rounded-2xl border border-[#e5e1d8] bg-[#fbfaf7]/75 p-5"><Icon className="h-5 w-5 text-[#b48858]" /><h2 className="mt-5 text-sm font-extrabold tracking-[-0.04em]">{title}</h2><p className="mt-2 text-xs leading-5 text-[#788078]">{description}</p></div>)}</section>
    </div>
  </main>;
}
