import { startLogin } from "@/const";
import { ArrowRight, BookOpen, CalendarDays, Footprints, ShieldCheck, Sparkles, Sprout, TimerReset, X } from "lucide-react";
import { useState } from "react";

const benefits = [
  { icon: TimerReset, title: "시간 기록", description: "앉아 있는 시간과 몰입한 시간을 있는 그대로 남겨요." },
  { icon: CalendarDays, title: "일정 사이의 틈", description: "기록을 캘린더 위에서 직접 조정하며 하루를 정리해요." },
  { icon: Footprints, title: "움직임의 흐름", description: "걸음 수와 집중 시간을 함께 보며 나만의 패턴을 찾아요." },
];

export default function Landing() {
  const [helpOpen, setHelpOpen] = useState(false);
  return <main className="min-h-screen bg-[#f8fafc] px-5 py-6 text-[#18332a] sm:px-8 sm:py-8"><div className="mx-auto max-w-[1180px]">
    <header className="flex items-center justify-between"><div className="flex items-center gap-3"><img src="/manus-storage/startpoint-logo_afef8c07.webp" alt="시작점 로고" className="h-11 w-11 rounded-2xl object-cover shadow-[0_8px_18px_rgba(61,220,132,0.25)]" /><div><p className="text-xl font-bold tracking-[-0.07em] text-[#18332a]">시작점</p><p className="text-[10px] font-bold tracking-[0.12em] text-[#7c9388]">LIFE RHYTHM</p></div></div><button onClick={() => setHelpOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-white px-3.5 py-2.5 text-xs font-bold text-[#46665a] shadow-sm ring-1 ring-[#e3eaf0] transition hover:bg-[#effff5]"><BookOpen className="h-4 w-4 text-[#22aa62]" />앱 사용 도움말</button></header>
    <section className="relative mt-12 overflow-hidden rounded-[34px] bg-[#18332a] px-6 py-8 text-white shadow-[0_24px_60px_rgba(24,51,42,0.16)] sm:mt-16 sm:px-12 sm:py-14"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-[#3ddc84]/20 blur-3xl" /><div className="absolute bottom-[-100px] left-[45%] h-64 w-64 rounded-full bg-[#3ddc84]/10 blur-3xl" /><div className="relative grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#3ddc84]/30 bg-[#3ddc84]/10 px-3 py-1.5 text-[11px] font-bold text-[#a9f5c9]"><span className="h-1.5 w-1.5 rounded-full bg-[#3ddc84]" />생활 리듬을 가볍게 바꾸는 앱</span><h1 className="mt-6 text-[34px] font-bold leading-[1.13] tracking-[-0.08em] sm:text-[52px]">앉아 있는 하루에도<br /><span className="text-[#3ddc84]">움직임의 틈</span>을 만들어요.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[#d4e8de] sm:text-base">좌석 시간과 공부·업무 집중 시간을 기록하고, 캘린더와 걸음 수 안에서 나만의 하루 흐름을 찾아보세요.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => startLogin()} className="inline-flex items-center gap-2 rounded-2xl bg-[#3ddc84] px-5 py-3.5 text-sm font-bold text-[#093d27] shadow-[0_12px_24px_rgba(61,220,132,0.18)] transition hover:bg-[#6fe8a2] active:scale-[0.97]">내 리듬 시작하기 <ArrowRight className="h-4 w-4" /></button><button onClick={() => setHelpOpen(true)} className="inline-flex items-center gap-2 rounded-2xl border border-white/20 bg-white/5 px-5 py-3.5 text-sm font-bold text-white transition hover:bg-white/10"><BookOpen className="h-4 w-4" />먼저 알아보기</button></div></div><div className="relative rounded-[28px] border border-white/10 bg-white/[0.07] p-5 backdrop-blur-sm sm:p-7"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[#a9f5c9]">오늘의 리듬 미리보기</p><span className="rounded-full bg-[#3ddc84]/15 px-2.5 py-1 text-[10px] font-bold text-[#a9f5c9]">내 기록</span></div><div className="mt-5 space-y-3"><div className="rounded-2xl bg-white/[0.08] p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-[#d4e8de]">오늘의 흐름</span><span className="text-xs font-bold text-[#3ddc84]">기록 준비</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[42%] rounded-full bg-[#3ddc84]" /></div></div><div className="rounded-2xl bg-[#3ddc84] p-4 text-[#093d27]"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] opacity-70">지금 가능한 시작</p><p className="mt-2 text-lg font-bold tracking-[-0.05em]">집중 시간 기록하기</p><p className="mt-1 text-xs font-medium opacity-75">라벨 · 타이머 · 캘린더 연결</p></div><TimerReset className="h-5 w-5" /></div></div><div className="flex items-center justify-between px-1 text-xs text-[#b9d6ca]"><span>오늘의 회복 잎</span><span className="font-bold text-[#a9f5c9]">기록으로 자라요</span></div></div></div></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3">{benefits.map(({ icon: Icon, title, description }) => <article key={title} className="rounded-3xl bg-white p-5 ring-1 ring-[#e3eaf0]"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#e9fff1] text-[#22aa62]"><Icon className="h-4 w-4" /></div><h2 className="mt-4 text-sm font-bold text-[#29463b]">{title}</h2><p className="mt-2 text-xs leading-5 text-[#7a9087]">{description}</p></article>)}</section>
    <section className="mt-7 flex flex-col items-center justify-between gap-4 rounded-3xl border border-[#e3eaf0] bg-white px-5 py-4 sm:flex-row"><p className="text-xs font-semibold text-[#6d8278]">로그인하면 나만의 시간·활동 기록이 계정에 안전하게 이어집니다.</p><button onClick={() => startLogin()} className="inline-flex items-center gap-2 rounded-xl bg-[#3ddc84] px-4 py-2.5 text-xs font-bold text-[#093d27] transition hover:bg-[#6fe8a2]"><Sprout className="h-3.5 w-3.5" />로그인하고 시작하기</button></section>
  </div>{helpOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#18332a]/35 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-label="앱 사용 도움말" className="w-full max-w-md rounded-[30px] bg-white p-6 shadow-2xl sm:p-7"><div className="flex items-center justify-between"><div><span className="text-[10px] font-bold tracking-[0.16em] text-[#22aa62]">HOW IT WORKS</span><h2 className="mt-1 text-xl font-bold tracking-[-0.06em] text-[#224336]">시작점 사용 흐름</h2></div><button onClick={() => setHelpOpen(false)} aria-label="도움말 닫기" className="grid h-9 w-9 place-items-center rounded-xl bg-[#f3f7f5] text-[#799087]"><X className="h-4 w-4" /></button></div><div className="mt-6 space-y-3">{[["01", "시간 시작하기", "좌석 또는 집중 타이머를 시작하고, 필요할 때 일시정지하세요."], ["02", "흐름 다듬기", "완료된 기록은 일·주 캘린더에서 드래그하여 직접 조정할 수 있어요."], ["03", "움직임 이해하기", "일별 걸음 수와 시간 기록을 함께 보며 나에게 맞는 리듬을 찾아요."]].map(([number, title, description]) => <div key={number} className="flex gap-3 rounded-2xl bg-[#f8fafc] p-4"><span className="text-xs font-bold text-[#3ddc84]">{number}</span><div><p className="text-sm font-bold text-[#345b4b]">{title}</p><p className="mt-1 text-xs leading-5 text-[#7b9187]">{description}</p></div></div>)}</div><button onClick={() => startLogin()} className="mt-6 w-full rounded-2xl bg-[#3ddc84] py-3.5 text-sm font-bold text-[#093d27] transition hover:bg-[#6fe8a2] active:scale-[0.98]">내 리듬 시작하기</button></section></div>}</main>;
}
